kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
          env:
            - name: PROVISIONER_NAME
              value: {{.Values.nfs.provisioner_name}}
            - name: NFS_SERVER
              value: {{.Values.nfs.server}}
            - name: NFS_PATH
              value: {{.Values.nfs.path}}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{.Values.nfs.server}}
            path: {{.Values.nfs.path}}
