apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
spec:
  containers:
    - name: internal-kubectl
      image: kaemaa/app-builder
      command:
        - "sleep"
      args:
        - "600"
  serviceAccountName: gitlab-service-account