apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-config
data:
  metrics.conf: |
    server {
      listen 8989;
      server_name _;
      location /metrics {
          stub_status on;
      }
    }