apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-2-deployment
spec:
  selector:
    matchLabels:
      app: web-2
  replicas: 1
  template:
    metadata:
      labels:
        app: web-2
    spec:
      containers:
      - name: web-2-app
        image: kmdr7/web-landing-2:latest
        ports:
        - containerPort: 80
        resources:
          requests:
              cpu: 100m
              memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: storage-volume
          mountPath: /prometheus/
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: web2-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web2-storage
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-2-service
spec:
  type: ClusterIP
  selector:
    app: web-2
  ports:
    - name: web-2
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-2-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - web-2.mykloud.andikaahmad.com
      secretName: letsencrypt-prod-issuer
  rules:
  - host: web-2.mykloud.andikaahmad.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-2-service
            port:
              number: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-2-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-2-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50