apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-1-deployment
spec:
  selector:
    matchLabels:
      app: web-1
  replicas: 1
  template:
    metadata:
      labels:
        app: web-1
    spec:
      containers:
      - name: web-1-app
        image: kmdr7/web-landing-1:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-1-service
spec:
  type: NodePort
  selector:
    app: web-1
  ports:
    - name: web-1
      protocol: TCP
      port: 80
      targetPort: 80
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: web-1-ingress
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "true"
#     certmanager.k8s.io/issuer: lets-selfsigned
#     kubernetes.io/ingress.class: "nginx"
# spec:
#   tls:
#     - hosts:
#       - web-1.mykloud.lokal
#       secretName: lets-selfsigned-cert-tls
#   rules:
#   - host: web-1.mykloud.lokal
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: web-1-service
#           servicePort: 80