apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
spec:
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 1; done"]
        volumeMounts:
        - name: nfs
          mountPath: /var/nfs
      volumes:
      - name: nfs
        nfs:
          server: 192.168.10.210
          path: /var/nfs-share/
