kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PROVISIONER_NAME
              value: mykloud.lokal/nfs
            - name: NFS_SERVER
              value: 192.168.10.12
            - name: NFS_PATH
              value: /var/nfs-share
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.10.12
            path: /var/nfs-share
