apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mykloud-mariadb
  serviceName: mykloud-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mykloud-mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mariadb:10.5.4
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_USER
            value: "mykloud"
          - name: MYSQL_PASSWORD
            value: "mykloud"
          - name: MYSQL_DATABASE
            value: "mykloud"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "managed-nfs-storage"
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mykloud-mariadb
  labels:
    app: mykloud-mariadb
spec:
  ports:
  - port: 3306
    name: db
  clusterIP: None
  selector:
    app: mykloud-mariadb