apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-2
spec:
  selector:
    matchLabels:
      app: redis-2
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-2
    spec:
      containers:
      - name: redis
        image: redis:5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.3.5-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 9121
---
kind: Service
apiVersion: v1
metadata:
  name: redis-2
spec:
  selector:
    app: redis-2
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: prom-mon
    protocol: TCP
    port: 9121
    targetPort: 9999