apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-deployment-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'mykloud-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.10.201:9100']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'kube-scheduler-service'
        static_configs:
          - targets: ['scheduler-service.kube-system.svc.cluster.local:10251']
      - job_name: 'mykloud-metrics'
        scrape_interval: 5s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: true
            action: keep
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_endpoint_port_name, __meta_kubernetes_endpoint_port_protocol, __meta_kubernetes_service_name]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+);(.*);(.*);(.*)
            replacement: _${3}._${4}.${5}.default:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            separator: ;
            regex: prom-mon
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: pod
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_service_name]
            separator: ;
            regex: (.*)
            target_label: service
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_service_name]
            separator: ;
            regex: (.*)
            target_label: job
            replacement: $1
            action: replace