kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      receiver: slack
      group_by: ['job']
      group_wait: 10s
      repeat_interval: 5m
    receivers:
      - name: slack
        slack_configs:
          - api_url: https://hooks.slack.com/services/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
            channel: '#kubernetes-alertmanager'