apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  slack.tmpl: |-
    {{range .Alerts}}{{.Annotations.title}}{{end}}
    {{range .Alerts}}{{.Annotations.description}}{{end}}