apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/issuer: lets-selfsigned
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - prometheus.mykloud.lokal
      secretName: lets-selfsigned-cert-tls
  rules:
  - host: prometheus.mykloud.lokal
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090